### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by jwflory** [Ilhasoft/bothub-webapp#1305]
# Summary

This repository does not use an Open Source license and instead follows default copyright law

# Background

In order to be clear to others about how reuse, changes, and redistribution terms work, select a permissive or copyleft Open Source license to govern the legal framework of how your project operates. If a license is not selected and added to the work, it is considered a "source-available" project and is not an open-source work. A non-existent license appears to be chosen for this repo (AGLP 3.0). Perhaps you meant to use the [AGPL-3.0](https://www.gnu.org/licenses/agpl-3.0.txt)? 

From GitHub's official documentation on [licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

You can also find more details in the [UNICEF Inventory Legal & Business Aspects reading list](https://unicef.github.io/inventory/legal-policy/reading-list/).

# Details

See GitHub's official documentation on [how to license a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). This should fit into an existing licensing strategy for your organization.

# Outcome

Clear policy and rules on how others can engage with your intellectual property, adapted to your business model

**Comment by johncordeiro** [comment]
Thanks for reaching out @jwflory , we've added the proper open source license for the project and also fixed the wrong information in the README file.
