### ISSUE TITLE
BhField errors prop can receive list of objects

### ISSUE THREAD

**Issue by douglasppaz** [Ilhasoft/bothub-webapp#149]
e.g
Input:
`[{"label": "...", "start": "..."}, {"label": "..."}]`

Output in bh-input:
```
- label: ...
  start: ...
- label: ...
```

e.g
Input:
`['error 1', {"label": "error 2", "start": "error 3"}]`

Output in bh-input:
```
- error 1
- label: error 2
  start: error 3
```

**Comment by douglasppaz** [comment]
@victor-dantas report progress...

**Comment by victor-dantas** [comment]
bug fixed on -> https://github.com/Ilhasoft/bothub-webapp/pull/153
