### ISSUE TITLE
Error on entity characters validation

### ISSUE THREAD

**Issue by johncordeiro** [Ilhasoft/bothub-webapp#177]
When you try to train a new example on Bothub, there is a validation on the value which is wrong. The characters validation needs to be done just by entities and labels names.

<img width="1093" alt="screen shot 2018-09-10 at 8 43 23 am" src="https://user-images.githubusercontent.com/6073075/45299167-1a7f6d00-b4e1-11e8-9678-6710ecb0ceea.png">

**Comment by douglasppaz** [comment]
The formatters is apply in input component but not replicate to Vue custom input component.

E.g. 1:
![image](https://user-images.githubusercontent.com/8301135/45300209-1b65ce00-b4e4-11e8-8b87-dd33df7528fe.png)
![image](https://user-images.githubusercontent.com/8301135/45300381-9333f880-b4e4-11e8-8277-7c8dfdc549b4.png)

E.g. 2:
![image](https://user-images.githubusercontent.com/8301135/45300469-cbd3d200-b4e4-11e8-9ade-e222683f2d19.png)
![image](https://user-images.githubusercontent.com/8301135/45300482-d726fd80-b4e4-11e8-8087-08870b7157f1.png)

@victor-dantas fix this and implement tests.
