### ISSUE TITLE
Button "More" -> Infinite load

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub-webapp#178]
While you train a bot (BEFORE tapping train), if you try to review the old phrases you need to tap the button "More" to load a new phrase list, but after tapping, it shows the loading animation eternaly.
![captura de tela 2018-09-10 as 10 38 12](https://user-images.githubusercontent.com/38072244/45300778-a5fafd00-b4e5-11e8-8b68-436cfb5d295c.png)

**Comment by douglasppaz** [comment]
Mixed Content raised...
![image](https://user-images.githubusercontent.com/8301135/45300952-21f54500-b4e6-11e8-91aa-0794d70bfc0d.png)

**Comment by douglasppaz** [comment]
Problem generated by bothub-engine infrastructure. The next link for more examples is generated by bothub-engine, the load balance serve HTTP and HTTPS in 80 port and the app interpretered this as HTTP request.
